### ISSUE TITLE
Please specify exact versions of dependencies

### ISSUE THREAD

**Issue by mbrukman** [meltwater/jugri#9]
Thanks for putting together and releasing this package!

The [`requirements.txt`][requirements-txt] currently just says:

```
pandas
gremlinpython
```

which does not list specific dependency versions (similarly to the `README.md`), but as these libraries evolve, JUGRI may not be compatible with the latest version of either of these libraries and may fail to work with them.

Could you please specify the exact dependency versions you've successfully used and test with into `requirements.txt` so that it's easy to recreate the same environment you've found to work for you? That will make it easier for all future users of this tool.

Thanks!

[requirements-txt]:  https://github.com/meltwater/jugri/blob/b9cabee4446d7893a93e5e2d2c30d50f30506645/requirements.txt

**Comment by djlancelot** [comment]
Sorry, for not fixing it earlier @mbrukman . The latest version [0.5.2] includes the compatible versions.

**Comment by mbrukman** [comment]
Thanks, @djlancelot!
